aa: null
alpha_layer: 0.1
amp: false
amp_dtype: float16
amp_impl: native
asl_gamma_neg: 1
asl_gamma_pos: 1
asl_thresh_shifting: 1
aug_repeats: 0
aug_splits: 0
batch_size: 32
bce_loss: false
bce_loss_weight: 1
bce_pos_weight: null
bce_sum: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_hist: 10
class_map: ./classmap/classmap.pkl
clip_grad: null
clip_mode: norm
color_jitter: 0.4
color_jitter_prob: null
cooldown_epochs: 0
crop_pct: null
crule_loss_weight: 0.2
csv_tree: ./data/small-collomboles/hierarchy.csv
cutmix: 0.0
cutmix_minmax: null
data: null
data_dir: ./data/small-collomboles/dataset
dataset: ''
dataset_download: false
dataset_trust_remote_code: false
decay_epochs: 90
decay_milestones:
- 90
- 180
- 270
decay_rate: 0.1
device: cuda
device_modules: null
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
drule_loss_weight: 0.2
epoch_repeats: 0.0
epochs: 100
erule_loss_weight: 0.2
eval_metric: top1
experiment: ''
fast_norm: false
fuser: ''
gaussian_blur_prob: null
gp: null
grad_accum_steps: 1
grad_checkpointing: false
grayscale_prob: null
hce_alpha: 0.1
hce_loss: false
head_init_bias: null
head_init_scale: null
hflip: 0.5
img_size: null
in_chans: null
initial_checkpoint: ''
input_img_mode: null
input_key: null
input_size:
- 3
- 224
- 224
interpolation: ''
jsd_loss: false
layer_decay: null
local_rank: 0
log_interval: 50
log_wandb: false
logicseg: false
logicseg_method: bce
lr: 0.0003
lr_base: 0.1
lr_base_scale: ''
lr_base_size: 256
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 0
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: resnet50.a1_in1k
model_dtype: null
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
model_ema_warmup: false
model_kwargs: {}
momentum: 0.9
no_aug: true
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
num_classes: 79
opt: lamb
opt_betas: null
opt_eps: null
opt_kwargs: {}
output: ./checkpoint
patience_epochs: 10
pin_mem: false
pretrained: true
pretrained_path: null
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
sched_on_updates: false
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
synchronize_step: false
target_key: null
target_loss_weight: 1
torchcompile: null
torchcompile_mode: null
torchscript: false
train_crop_mode: null
train_interpolation: random
train_num_samples: null
train_split: train
tta: 0
use_multi_epochs_loader: false
val_num_samples: null
val_split: validation
validation_batch_size: 64
vflip: 0.0
wandb_project: null
wandb_resume_id: ''
wandb_tags: []
warmup_epochs: 5
warmup_lr: 1.0e-05
warmup_prefix: false
weight_decay: 0.01
worker_seeding: all
workers: 8
