model: resnet50
checkpoint: "output/train_bis/BCE__1/model_best.pth.tar"
data_dir: "data/small-collomboles/dataset/test"
class_map: "data/small-collomboles/class_mapping.txt"
num_classes: 79

results_dir: "output/test_bis/bce_1_without_hier"
results_file: "bce_1_without_hier"

# conf_matrix: True

device: "cpu"