# Model
model: resnet50.a1_in1k 
pretrained: True

# Dataset
data_dir: "data/small-collomboles/dataset"
class_map: "classmap/classmap.pkl"
output: "output/train"
csv_tree: "data/small-collomboles/hierarchy.csv"
num_classes: 136
input_size:
- 3 
- 224
- 224 

# Hyperparameter
epochs: 100
b: 32 
vb: 64 
j: 8 
lr: 3e-4
batch_size: 32

# Optimizer
opt: "lamb"
sched: 'cosine'
weight_decay: 0.01
warmup_epochs: 5
logicseg: True
crule_loss_weight: 0
drule_loss_weight: 0
erule_loss_weight: 0
bce_loss_weight: 1
logicseg_method: "multi_bce"

# Augmentation
drop_path: 0.05 
smoothing: 0.1 
mixup: 0.2 
cutmix: 1.0 
hflip: 0.5 
aa: "rand-m7-mstd0.5"

# Device
# amp: True