
# Model
model: resnet50.a1_in1k
pretrained: true 

# Dataset
data_dir: "data/small-collomboles/dataset"
class_map: "data/small-collomboles/class_mapping.txt"
csv_tree: "data/small-collomboles/hierarchy.csv"
num_classes: 79

# Hyperparameter
epochs: 100
b: 32 
vb: 64 
j: 8 
lr: 3e-4

# Optimizer
opt: "lamb" 
sched: "cosine"
weight_decay: 0.01 
warmup_epochs: 5 
hce_loss: true
hce_alpha: 0.5
# Log
log-interval: 200 

# Augmentation
drop_path: 0.05 
smoothing: 0.1 
mixup: 0.2 
cutmix: 1.0 
hflip: 0.5 
aa: "rand-m7-mstd0.5"

# Device
amp: true